services:
  db:
    image: postgres
    command: -c ssl=off
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123qwe"
    ports:
      - "5432:5432"
    env_file:
      - ./.env