services:
  # testwb:
  #   build: ./
  #   command: ./main
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_PASSWORD=123qwe
  db:
    restart: always
    image: postgres:latest
    command: -c ssl=off
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123qwe"
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
    network_mode: bridge